blank_issues_enabled: false
contact_links:
  - name: name: bug_report
    url: https://github.com/YAPP-16th/Team_Android_2_Backend/
    about: create a bug report
  - name: pull_request
    url: https://github.com/YAPP-16th/Team_Android_2_Backend/
    about: Create a pull request
