version: '3.7'

services:
  teamplay-external-api:
    build:
      context: .
    container_name: teamplay-external-api
    environment:
      - VIRTUAL_HOST=api.fonnie.shop
      - LETSENCRYPT_HOST=api.fonnie.shop
      - LETSENCRYPT_EMAIL=sj.oh.yapp@gmail.com
      - VIRTUAL_PORT=8080
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
